### PR TITLE
refactor(strategy): fix issue with client id

### PR DESCRIPTION
**Pull request by qlaffont**
ref https://github.com/oauth-everything/passport-twitch/issues/6

👋 @Tschrock

### CODE REVIEW

**Comment by qlaffont** [comment]
@Tschrock you need something for the PR ?

**Comment by Tschrock** [comment]
Apologies for the delay, I was on vacation last week and didn't get to it before I left. Looks good at first glance - I'll try to get this merged tonight.

**Comment by qlaffont** [comment]
my bad ^^

**Comment by qlaffont** [comment]
@Tschrock did you forgot to push it on npm ? Or did we need to make changes ?

**Pull request merged**
